# Generated by Django 4.2.7 on 2023-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('topic_content', models.CharField(max_length=255)),
                ('topic_slug', models.SlugField(default='slug', max_length=255)),
                ('programming_languages', models.ManyToManyField(related_name='topic', to='codelang.language')),
            ],
        ),
    ]
