# Generated by Django 4.2.7 on 2023-11-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(default='slug', max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(max_length=255),
        ),
    ]
