# Generated by Django 4.2.7 on 2023-11-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
