# Generated by Django 4.2.7 on 2023-11-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelang', '0002_topic_topic_slug_alter_language_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
