# Generated by Django 4.2.7 on 2023-11-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelang', '0002_alter_topic_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_text',
            field=models.TextField(blank=True),
        ),
    ]
