# Generated by Django 4.2.7 on 2023-12-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codelang', '0003_topic_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_code',
            field=models.TextField(blank=True),
        ),
    ]
