# Generated by Django 4.2.7 on 2023-12-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codelang', '0004_topic_topic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_code',
        ),
    ]
